// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores tenant information for multi-tenant architecture
type Tenant struct {
	// Unique identifier for the tenant
	ID pgtype.UUID `json:"id"`
	// Display name of the tenant
	Name string `json:"name"`
	// Contact email for the tenant (case-insensitive, unique)
	Email string `json:"email"`
	// Optional domain for subdomain-based multi-tenancy
	Domain pgtype.Text `json:"domain"`
	// Whether the tenant is active and can access the system
	IsActive bool `json:"is_active"`
	// Timestamp when the tenant was created
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when the tenant was last updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
