// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteTenant(ctx context.Context, dollar_1 pgtype.UUID) error
	GetTenantByDomain(ctx context.Context, domain pgtype.Text) (Tenant, error)
	GetTenantByEmail(ctx context.Context, email string) (Tenant, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
