// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.flowcargo.com/support",
            "email": "support@flowcargo.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tenants": {
            "post": {
                "description": "Create a new tenant with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Create a new tenant",
                "parameters": [
                    {
                        "description": "Tenant creation parameters",
                        "name": "tenant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tenant.CreateTenantParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-tenant_Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    }
                }
            }
        },
        "/tenants/{id}": {
            "get": {
                "description": "Retrieve a tenant's information by their unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Get a tenant by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID (UUID format)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-tenant_Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing tenant's information by their unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Update a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID (UUID format)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tenant update parameters",
                        "name": "tenant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tenant.UpdateTenantParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-tenant_Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing tenant by their unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Delete a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID (UUID format)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-tenant_Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/restutils.APIResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "restutils.APIResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/restutils.ErrorDetail"
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "meta": {
                    "$ref": "#/definitions/restutils.Metadata"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "restutils.APIResponse-tenant_Tenant": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/tenant.Tenant"
                },
                "error": {
                    "$ref": "#/definitions/restutils.ErrorDetail"
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "meta": {
                    "$ref": "#/definitions/restutils.Metadata"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "restutils.ErrCode": {
            "type": "string",
            "enum": [
                "VALIDATION_ERROR",
                "NOT_FOUND",
                "INTERNAL_SERVER_ERROR",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "RESOURCE_CONFLICT",
                "DATABASE_ERROR",
                "EXTERNAL_SERVICE_ERROR",
                "METHOD_NOT_ALLOWED"
            ],
            "x-enum-varnames": [
                "ErrCodeValidation",
                "ErrCodeNotFound",
                "ErrCodeInternal",
                "ErrCodeUnauthorized",
                "ErrCodeForbidden",
                "ErrCodeConflict",
                "ErrCodeDatabase",
                "ErrCodeExternalService",
                "ErrCodeMethodNotAllowed"
            ]
        },
        "restutils.ErrorDetail": {
            "description": "Detailed error information including status code, error code, resource, and error messages",
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/restutils.ErrCode"
                        }
                    ],
                    "example": "VALIDATION_ERROR"
                },
                "errors": {
                    "type": "string",
                    "example": "validation failed: name is required"
                },
                "resource": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/restutils.Resource"
                        }
                    ],
                    "example": "tenant"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "restutils.Metadata": {
            "description": "Response metadata containing timestamp and other contextual information",
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "restutils.Resource": {
            "type": "string",
            "enum": [
                "tenant"
            ],
            "x-enum-varnames": [
                "ResourceTenant"
            ]
        },
        "tenant.CreateTenantParams": {
            "description": "Parameters for creating a new tenant account",
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "https://acme.com"
                },
                "email": {
                    "type": "string",
                    "example": "contact@acme.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Acme Corporation"
                }
            }
        },
        "tenant.Tenant": {
            "description": "Tenant account information with contact details and status",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "domain": {
                    "type": "string",
                    "example": "https://acme.com"
                },
                "email": {
                    "type": "string",
                    "example": "contact@acme.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Acme Corporation"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "tenant.UpdateTenantParams": {
            "description": "Parameters for updating tenant information (all fields optional except ID)",
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "https://newdomain.acme.com"
                },
                "email": {
                    "type": "string",
                    "example": "newemail@acme.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Acme Corporation Updated"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "FlowCargo API",
	Description:      "Multi-tenant cargo management system API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
